import { ParentClassPageData } from "./ParentClassPage.types";

export const parentClassPageMockData: ParentClassPageData = {
  "texts": {
    "t001": "Lớp cho cha mẹ",
    "t002": "Không ai ở bên con",
    "t003": "nhiều giờ bằng bạn.",
    "t004": "Một ngày trẻ có 1–2 giờ trị liệu. Còn lại là 22 giờ ở với bạn. Người quyết định con tiến nhanh hay chậm không phải trị liệu viên — mà là người dạy con trong những giờ đó.",
    "t005": "Lớp một ngày — 999.999đ",
    "t006": "Kèm riêng tám tuần",
    "t007": "Hai mức, tuỳ bạn đang cần gì",
    "t008": "Bạn có thể dành bao nhiêu thời gian để “tác chiến” ngay với con?",
    "t009": "MỨC 1 · PHỔ BIẾN NHẤT",
    "t010": "Lớp cha mẹ — một ngày (B247)",
    "t011": "Học trực tiếp hoặc trực tuyến · không cần nền tảng",
    "t012": "999.999đ",
    "t013": "Đã gồm sổ tay cha mẹ và bộ tài liệu phát tay",
    "t014": "Dành cho",
    "t015": "Cha mẹ vừa biết con có vấn đề, đang chờ lịch can thiệp, hoặc muốn hiểu con đang ở đâu trước khi quyết định bất cứ điều gì.",
    "t016": "Con bạn đang ở giai đoạn giao tiếp nào — và bậc kế tiếp là gì",
    "t017": "Danh sách kiểm tra các kỹ năng giao tiếp quan trọng, tự chấm được cho con",
    "t018": "Công thức dạy học: nói gì, làm gì, chờ bao lâu",
    "t019": "Tạo động lực cho con — vì sao con không hợp tác và làm sao để con muốn",
    "t020": "Ba hoạt động mẫu làm được ngay tối nay",
    "t021": "Chuyển bài học ở trường thành hoạt động ở nhà",
    "t022": "Phát triển từ vựng — dạy từ nào trước",
    "t023": "Xem clip ca thật tại lớp, có phân tích cùng giảng viên",
    "t024": "Bạn cầm về",
    "t025": "Sổ tay cha mẹ, bảng kiểm kỹ năng đã chấm cho con bạn, và ba hoạt động viết sẵn để làm ngay tuần này.",
    "t026": "Đăng ký lớp một ngày",
    "t027": "MỨC 2 · CẦM TAY CHỈ VIỆC",
    "t028": "Dạy con 24/7 (P247)",
    "t029": "Kèm riêng thực hành",
    "t030": "Học phí: liên hệ",
    "t031": "Số suất mỗi đợt có hạn vì là kèm riêng",
    "t032": "Dành cho",
    "t033": "Cha mẹ đã biết con cần gì nhưng làm ở nhà mãi không lên — hoặc ở xa, không đưa con đi can thiệp đều đặn được.",
    "t034": "Một kèm một",
    "t035": " — giảng viên xem chính con bạn, sửa chính cách bạn đang làm",
    "t036": "Đánh giá đầu vào",
    "t037": " và tư vấn chi tiết về số đo phát triển và mục tiêu của con",
    "t038": "Tám tuần đi cùng nhau",
    "t039": "10 bài học trên web",
    "t040": " — tự học, bất kì lúc nào",
    "t041": "Mỗi tuần một buổi Zoom riêng",
    "t042": " — 8 buổi cả khoá",
    "t043": "Mỗi tuần bạn ",
    "t044": "quay một clip cảnh dạy con",
    "t045": ", gửi trước để được xem và sửa",
    "t046": "Kế hoạch dạy con cá nhân hoá, may đo trên chính con bạn",
    "t047": "Được chỉnh khi làm sai — đây là thứ sách và lớp đông không cho được",
    "t048": "Đi kèm bộ sách ",
    "t049": "Dạy con 24/7",
    "t050": " làm tài liệu nền",
    "t051": "Bạn cầm về",
    "t052": "Một kế hoạch dạy con chạy được ở nhà, và quan trọng hơn: thói quen dạy đúng đã thành phản xạ — dạy được mọi lúc, mọi nơi, trong mọi hoạt động.",
    "t053": "Hỏi lịch coaching",
    "t054": "Nên bắt đầu từ đâu",
    "t055": "1",
    "t056": "Nếu bạn chưa biết con đang ở đâu",
    "t057": "Đi ",
    "t058": "khám và lượng giá",
    "t059": " trước, rồi mới chọn lớp. Học mà chưa biết con ở đâu thì học xong vẫn không biết áp dụng phần nào.",
    "t060": "2",
    "t061": "Nếu bạn muốn hiểu con và có việc làm ngay tối nay",
    "t062": "Lớp một ngày — 999.999đ",
    "t063": ". Một ngày, mang về sổ tay và ba hoạt động. Đây là mức đủ cho phần lớn gia đình.",
    "t064": "3",
    "t065": "Nếu bạn đã học rồi mà làm ở nhà vẫn không lên",
    "t066": "Dạy con 24/7 — kèm riêng tám tuần",
    "t067": ". Vấn đề lúc này không nằm ở kiến thức, mà ở chỗ chưa ai xem bạn làm và sửa cho bạn.",
    "t068": "Đọc trước cũng được",
    "t069": "Nếu bạn muốn tự tìm hiểu trước khi quyết định đi học, ba cuốn này là điểm bắt đầu rẻ nhất.",
    "t070": "0–5 tuổi",
    "t071": "“Bản đồ” 5 năm đầu đời của con",
    "t072": "Checklist phát triển theo giai đoạn và các dấu hiệu “cờ đỏ” để phát hiện sớm.",
    "t073": "199.000đ",
    "t074": "Đặt sách",
    "t075": "Giáo trình của khoá coaching",
    "t076": "Dạy con 24/7",
    "t077": "Chính là tài liệu nền của khoá kèm riêng. Đọc trước để vào khoá nhanh hơn.",
    "t078": "380.000đ",
    "t079": "Đặt sách",
    "t080": "Con muốn học nói",
    "t081": "100 từ đầu tiên của bé",
    "t082": "100 từ trẻ Việt nói sớm nhất, thống kê từ 600 trẻ ba miền. Dạy từ nào trước.",
    "t083": "245.000đ",
    "t084": "Đặt sách",
    "t085": "Xem cả 7 cuốn →",
    "t086": "Cha mẹ hay hỏi",
    "t087": "Tôi không có chuyên môn gì, học lớp một ngày có theo kịp không?",
    "t088": "Lớp một ngày được viết riêng cho cha mẹ, không yêu cầu nền tảng. Toàn bộ nội dung là quan sát con và làm được ngay ở nhà — không có thuật ngữ nào mà bạn phải tra cứu.",
    "t089": "Kèm riêng khác lớp một ngày ở chỗ nào?",
    "t090": "Lớp một ngày cho bạn ",
    "t091": "kiến thức và công cụ",
    "t092": ". Coaching cho bạn ",
    "t093": "người sửa cho bạn",
    "t094": " trong tám tuần — xem chính con bạn, xem chính cách bạn đang dạy, và chỉ ra chỗ bạn làm chưa đúng. Phần lớn cha mẹ không thiếu kiến thức, mà thiếu người nói “chỗ này chị làm sai rồi”.",
    "t095": "Tôi ở tỉnh xa, có tham gia được không?",
    "t096": "Khoá coaching ",
    "t097": "Dạy con 24/7",
    "t098": " hoàn toàn online nên ở đâu cũng học được. Lớp một ngày là học trực tiếp — nhắn Zalo để biết lịch mở lớp gần bạn nhất.",
    "t099": "Con tôi đang can thiệp ở trung tâm rồi, có cần học nữa không?",
    "t100": "Rất nên. Con bạn có 2–3 buổi trị liệu một tuần, còn lại là thời gian ở nhà. Cha mẹ biết cách kéo dài mục tiêu của trị liệu viên vào sinh hoạt hằng ngày thì con tiến nhanh hơn hẳn — đây là điều nghiên cứu về can thiệp lấy gia đình làm trọng tâm đã cho thấy nhiều năm nay.",
    "t101": "Học phí kèm riêng bao nhiêu và mở lớp khi nào?",
    "t102": "Vì là kèm riêng nên số suất mỗi đợt có hạn. Nhắn Zalo ",
    "t103": "0866620583",
    "t104": " để biết học phí, lịch đợt gần nhất và còn suất hay không.",
    "t105": "Bắt đầu bằng một tin nhắn",
    "t106": "Kể cho chúng tôi con bạn mấy tuổi và điều bạn lo nhất. Chúng tôi sẽ nói thẳng bạn nên đi lớp một ngày, vào coaching, hay chỉ cần mua một cuốn sách là đủ.",
    "t107": "Nhắn Zalo 0866620583",
    "t108": "Gọi ngay"
  },
  "images": {
    "img001": "/images/ban-o-5-nam-au-oi-cua-con-763c4a96.jpg",
    "img002": "/images/day-con-24-7-0c3aad87.jpg",
    "img003": "/images/100-tu-au-tien-cua-be-532c8917.jpg"
  },
  "links": {
    "link001": "#lop-cha-me/p1",
    "link002": "#lop-cha-me/p2",
    "link003": "https://zalo.me/0857389318",
    "link004": "https://zalo.me/0857389318",
    "link005": "#phu-huynh/kham",
    "link006": "#lop-cha-me/p1",
    "link007": "#lop-cha-me/p2",
    "link008": "https://zalo.me/0866620583",
    "link009": "https://zalo.me/0866620583",
    "link010": "https://zalo.me/0866620583",
    "link011": "#sach",
    "link012": "https://zalo.me/0866620583",
    "link013": "tel:0866620583"
  },
  "alts": {
    "alt001": "Bản đồ 5 năm đầu đời của con",
    "alt002": "Dạy con 24/7",
    "alt003": "100 từ đầu tiên của bé"
  },
  "placeholders": {}
};
