import { TrainingPageData } from "./TrainingPage.types";

export const trainingPageMockData: TrainingPageData = {
  "texts": {
    "t001": "Dành cho chuyên viên · Chương trình đào tạo",
    "t002": "Tháp đào tạo Dr Owl Academy",
    "t003": "Đọc từ dưới lên. ",
    "t004": "Âm ngữ trị liệu — bệ phóng — là nền",
    "t005": ": ai làm can thiệp cho trẻ khó khăn về ngôn ngữ cũng cần vượt qua. Sau đó chọn Chơi lớn hay Miệng xinh lời hay tuỳ hướng đi của bạn, hoặc đi cả hai. Bấm vào từng bậc để xem nội dung chi tiết.",
    "t006": "Nhánh Cha mẹ — đi riêng",
    "t007": "Lớp cha mẹ 1 ngày",
    "t008": "Học trực tiếp · không cần nền tảng",
    "t009": "999.999đ",
    "t010": "Dạy con 24/7",
    "t011": "Coaching 1–1 online · 8 tuần",
    "t012": "1 buổi Zoom + 1 clip mỗi tuần",
    "t013": "Cha mẹ muốn đi sâu hơn thì bước sang nhánh làm nghề, vào thẳng ",
    "t014": "Âm ngữ trị liệu Bậc 1",
    "t015": ".",
    "t016": "Đỉnh · Bậc 5",
    "t017": "Can thiệp đa trường phái",
    "t018": "Tích hợp các công cụ và phương pháp trên cùng một đứa trẻ",
    "t019": "Hành vi ngôn ngữ",
    "t020": "Suy đoán tâm trí",
    "t021": "Can thiệp sớm + PROMPT",
    "t022": "Tích hợp giác quan – vận động",
    "t023": "Vào đỉnh cần: ",
    "t024": "xong ÂNTL ba bậc",
    "t025": " và trọn ",
    "t026": "ít nhất một chuyên khoa",
    "t027": "Cành 1 · Bậc 4",
    "t028": "CHƠI LỚN",
    "t029": "Chuyên khoa phát triển & vui chơi",
    "t030": "C1 Chơi lớn",
    "t031": "C2 Nói chơi",
    "t032": "C3 Chơi cùng giác quan",
    "t033": "Cành 2 · Bậc 4",
    "t034": "MIỆNG XINH LỜI HAY",
    "t035": "Chuyên khoa âm lời nói",
    "t036": "C1 Cấu âm",
    "t037": "C2 Âm vị",
    "t038": "C3 Bàn tay kì diệu",
    "t039": "C4 Trẻ nói khó và đồng mắc",
    "t040": "Hai cành học song song được · ",
    "t041": "MXLH Cấp 4 bắt buộc phải có ÂNTL Bậc 1 và Bậc 2",
    "t042": "Thân cây · Bậc 3",
    "t043": "ÂNTL Bậc 3 — Chuyên sâu",
    "t044": "AAC chuyên sâu · may đo chương trình trị liệu âm ngữ phức hợp · triển khai hoạt động dạy · lượng giá động",
    "t045": "Thân cây · Bậc 2",
    "t046": "ÂNTL Bậc 2 — Trị liệu giao tiếp",
    "t047": "Công thức thiết kế mục tiêu · tháp dạy học 4Th · quy trình can thiệp khép kín · kịch bản trị liệu",
    "t048": "Nền · Bậc 1 — ai làm nghề cũng phải qua",
    "t049": "ÂNTL Bậc 1 — May đo & Lượng giá",
    "t050": "Bảng kiểm lâm sàng giao tiếp chức năng · mốc phát triển · dấu hiệu cảnh báo · phân tích case thực tế · viết mục tiêu chuẩn y khoa · không yêu cầu nền tảng",
    "t051": "Danh hiệu đạt được",
    "t052": "Mỗi bậc, mỗi cấp",
    "t053": "Chứng nhận hoàn thành",
    "t054": "Trọn hệ Âm ngữ trị liệu",
    "t055": "Trị liệu viên Tài năng — hệ Âm ngữ trị liệu",
    "t056": "Trọn hệ Chơi lớn",
    "t057": "Trị liệu viên Tài năng — hệ Trị liệu ứng dụng Chơi",
    "t058": "Trọn hệ Miệng xinh lời hay",
    "t059": "Trị liệu viên Tài năng — hệ Kích tạo âm chuẩn y khoa",
    "t060": "Đỉnh tháp",
    "t061": "⭐ Trị liệu viên Tinh hoa",
    "t062": "Chuyển giao & giám sát",
    "t063": "Thực hành lâm sàng có giám sát · quyền dùng giáo trình & biểu mẫu · đào tạo in-house · duyệt hồ sơ ca. Bốn hạng mục tính phí riêng.",
    "t064": "Xem chi tiết",
    "t065": "Xem nội dung từng bậc ↓",
    "t066": "Bắt đầu từ đâu",
    "t067": "Bạn đang vướng ở đâu?",
    "t068": "Đừng chọn khoá theo tên. Hãy chọn theo trẻ đang làm bạn bế tắc — rồi đi hết hệ của nó.",
    "t069": "“Tôi mới vào nghề, nhìn trẻ mà không biết bắt đầu từ đâu.”",
    "t070": "Âm ngữ trị liệu Bậc 1 — Bệ phóng",
    "t071": "Học một cấp là có ngay quy trình lượng giá và bộ biểu mẫu dùng được từ ca đầu tiên.",
    "t072": "Xem cấp này →",
    "t073": "“Tôi lượng giá được rồi, nhưng vào buổi dạy vẫn lúng túng.”",
    "t074": "ÂNTL Bậc 2",
    "t075": "Quy trình 6 bước, bốn thang gợi nhắc, session note mẫu — buổi nào cũng biết mình đang làm gì.",
    "t076": "Xem cấp này →",
    "t077": "“Trẻ không chịu chơi cùng, không luân phiên, không bắt chước.”",
    "t078": "Chơi lớn Cấp 1 → Cấp 2",
    "t079": "Đọc được bậc chơi của trẻ, rồi dùng chính cuộc chơi làm công cụ kéo trẻ vào tương tác và bật âm.",
    "t080": "Xem cấp này →",
    "t081": "“Trẻ kén ăn, sợ tiếp xúc, che tai, chạy nhảy không ngừng…”",
    "t082": "Chơi lớn Cấp 3 — Chơi cùng giác quan",
    "t083": "Gỡ rào giác quan đang chặn lời nói, thay vì kết luận trẻ không hợp tác.",
    "t084": "Xem cấp này →",
    "t085": "“Trẻ ngọng, tôi chỉnh mãi một âm mà không hết.”",
    "t086": "Miệng xinh lời hay Cấp 1 → Cấp 2",
    "t087": "Vì lỗi nằm ở hệ thống âm vị chứ không ở một âm. Học đọc hệ thống trước khi tập.",
    "t088": "Xem cấp này →",
    "t089": "“Trẻ hiểu hết, muốn nói, mà miệng không bắt chước tôi được.”",
    "t090": "Miệng xinh lời hay Cấp 3 → Cấp 4",
    "t091": "Đặt tay đúng chỗ để giúp trẻ tạo được âm, rồi dựng chương trình vận động lời nói ba tháng.",
    "t092": "Xem cấp này →",
    "t093": "Không thấy tình huống của bạn? Nhắn Zalo ",
    "t094": "0866620583",
    "t095": " — kể ca bạn đang vướng, chúng tôi chỉ đúng cấp cần học.",
    "t096": "Chi tiết",
    "t097": "Mười cấp — nội dung đầy đủ",
    "t098": "Tất cả",
    "t099": "Âm ngữ trị liệu — nền",
    "t100": "Chơi lớn",
    "t101": "Miệng xinh lời hay",
    "t102": "Cách bán:",
    "t103": " mua lẻ từng cấp theo thứ bậc — học một cấp rồi dừng vẫn có giá trị trọn vẹn, vì mỗi cấp kết thúc bằng một sản phẩm bạn làm trên ca thật. Đăng ký trọn hệ thì có ưu đãi và được xét danh hiệu ",
    "t104": "Trị liệu viên Tài năng",
    "t105": " của hệ đó. Học phí và lịch khai giảng thay đổi theo đợt — nhắn Zalo ",
    "t106": "0866620583",
    "t107": " hoặc vào ",
    "t108": "nhóm Zalo cập nhật lịch",
    "t109": ".",
    "t110": "Â",
    "t111": "ÂM NGỮ TRỊ LIỆU",
    "t112": "TS.BS. Nguyễn Hoàng Oanh",
    "t113": "Thân cây. Ai làm nghề can thiệp cũng phải qua nền này trước, dù sau đó đi hướng chơi hay hướng âm lời nói.",
    "t114": "Hoàn thành trọn hệ →",
    "t115": " Trị liệu viên Tài năng — hệ Âm ngữ trị liệu",
    "t116": "Bậc 1",
    "t117": "May đo & Lượng giá",
    "t118": "Cửa vào của cả hệ thống. Học xong bạn nhìn một đứa trẻ và gọi được tên: bé đang ở đâu, thiếu gì, và điều gì phải làm trước.",
    "t119": "Nội dung chi tiết",
    "t120": "Giao tiếp",
    "t121": "Mốc phát triển ngôn ngữ và phát triển từ vựng theo tuổi",
    "t122": "Chức năng giao tiếp",
    "t123": "Dấu hiệu cảnh báo",
    "t124": "Sàng lọc và phân loại",
    "t125": "Nền phát triển kỹ năng chơi",
    "t126": "Bảng kiểm lâm sàng giao tiếp chức năng",
    "t127": "Phân tích case thực tế lượng giá",
    "t128": "Ưu tiên hoá và viết mục tiêu chuẩn y khoa",
    "t129": "Học xong có năng lực",
    "t130": "Hoàn thành hồ sơ lượng giá giao tiếp hoàn chỉnh trên trẻ của bạn, với những mục tiêu ưu tiên và cá nhân hoá.",
    "t131": "Điều kiện",
    "t132": " Không yêu cầu nền tảng — mở cho cả phụ huynh muốn học sâu",
    "t133": "Giáo trình",
    "t134": " Bản đồ 5 năm đầu đời · 100 từ đầu tiên",
    "t135": "Hình thức",
    "t136": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t137": "Hỏi lịch & học phí →",
    "t138": "Bậc 2",
    "t139": "Trị liệu giao tiếp",
    "t140": "Có số đo phát triển, bản đồ, mục tiêu… — dạy thế nào để trẻ tuần sau tiến bộ hơn tuần này. Đây là cấp gỡ được cảm giác lúng túng khi vào buổi trị liệu.",
    "t141": "Nội dung chi tiết",
    "t142": "Công thức thiết kế mục tiêu",
    "t143": "Qui trình chuỗi dạy học",
    "t144": "Tháp dạy học 4Th",
    "t145": "Quy trình can thiệp khép kín",
    "t146": "Kịch bản trị liệu chi tiết",
    "t147": "Dạy chức năng và phương tiện giao tiếp mới",
    "t148": "Phát triển ngôn ngữ chức năng",
    "t149": "Tổng quát hoá và làm việc liên ngành",
    "t150": "Học xong có năng lực",
    "t151": "Triển khai thành công các kế hoạch can thiệp, đo lường được kết quả, điều chỉnh linh hoạt, ứng phó khẩn cấp.",
    "t152": "Điều kiện",
    "t153": " Đã học Bậc 1",
    "t154": "Giáo trình",
    "t155": " Dạy con 24/7",
    "t156": "Hình thức",
    "t157": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t158": "Hỏi lịch & học phí →",
    "t159": "Bậc 3",
    "t160": "Chuyên sâu — May đo chương trình trị liệu âm ngữ phức hợp",
    "t161": "Sử dụng tích hợp nhiều công cụ AAC và các kĩ thuật dạy ngôn ngữ.",
    "t162": "Nội dung chi tiết",
    "t163": "AAC chuyên sâu: kim tự tháp và mức độ giao tiếp",
    "t164": "PECS và AAC",
    "t165": "Chương trình may đo về trị liệu ngôn ngữ cho từng trẻ",
    "t166": "Triển khai hoạt động dạy — biến mục tiêu trên giấy thành nhiều buổi dạy cụ thể và đa dạng",
    "t167": "Lượng giá động",
    "t168": " — đo tiến bộ ngay trong lúc dạy, không chỉ đo đầu và cuối",
    "t169": "Cách tự phát hiện lỗi của mình",
    "t170": "Viết báo cáo chuẩn · phản hồi và tư vấn gia đình",
    "t171": "Học xong có năng lực",
    "t172": "Triển khai thành công các tiết dạy có phối hợp các công cụ AAC và quản lý hành vi, phát triển đa dạng hệ thống học liệu dạy học, phát triển ma trận hoạt động dạy.",
    "t173": "Điều kiện",
    "t174": " Đã học Bậc 2",
    "t175": "Giáo trình",
    "t176": " “29 giọng nói”",
    "t177": "Hình thức",
    "t178": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t179": "Hỏi lịch & học phí →",
    "t180": "C",
    "t181": "CHƠI LỚN",
    "t182": "TS.BS. Nguyễn Hoàng Oanh",
    "t183": "Cành thứ nhất. Dành cho trẻ chưa tham gia ổn định trong các hoạt động chơi, chưa luân phiên, chưa bắt chước — và cho trẻ bị giác quan chặn đường đến lời nói.",
    "t184": "Hoàn thành trọn hệ →",
    "t185": " Trị liệu viên Tài năng — hệ Trị liệu ứng dụng Chơi",
    "t186": "Cấp 1",
    "t187": "Chơi lớn — Đọc được cuộc chơi",
    "t188": "Bạn đã bao giờ ngồi cả buổi với một đứa trẻ, ghi vào phiếu “bé chơi ngoan, hợp tác tốt”, rồi tuần sau đọc lại và không biết bắt đầu dạy từ đâu?",
    "t189": "Nội dung chi tiết",
    "t190": "Lượng giá được kĩ năng chơi của trẻ trên case lâm sàng",
    "t191": "Nhận biết hành vi tự kích thích và né tránh tương tác trong lúc trẻ chơi",
    "t192": "Nắm vững các chỉ số trong trạng thái chơi của trẻ",
    "t193": "Quy trình dạy chơi 4Th và vai trò linh hoạt của người dạy",
    "t194": "Xử lý sáu sự cố hay gặp",
    "t195": "Học xong có năng lực",
    "t196": "Lượng giá chơi và xây dựng kế hoạch chơi có mục tiêu.",
    "t197": "Điều kiện",
    "t198": " Đã học Âm ngữ trị liệu Bậc 1",
    "t199": "Giáo trình",
    "t200": " Chơi lớn (Tập 1)",
    "t201": "Hình thức",
    "t202": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t203": "Hỏi lịch & học phí →",
    "t204": "Cấp 2",
    "t205": "Nói chơi — Chơi để trẻ hay nói",
    "t206": "Có những buổi chơi rất vui. Trẻ cười, trẻ nhìn bạn, trẻ chờ tới lượt. Nhưng tuần này qua tuần khác vẫn chưa có từ ngữ nào bật ra từ trẻ.",
    "t207": "Nội dung chi tiết",
    "t208": "Xây dựng 7 năng lực nền trước lời nói",
    "t209": "Định vị trẻ trên năm mức giao tiếp phi ngôn ngữ",
    "t210": "Chín chiến lược khiến trẻ muốn nói",
    "t211": "Sáu kỹ thuật giúp trẻ nhớ và dùng từ",
    "t212": "Chọn trò chơi theo tầng",
    "t213": "Đặt điểm bật âm vào đúng trò chơi",
    "t214": "Học xong có năng lực",
    "t215": "Sử dụng thành thạo ma trận trò chơi – ngôn ngữ và lên kế hoạch “chơi để nói” cho trẻ của mình.",
    "t216": "Điều kiện",
    "t217": " Đã học Cấp 1",
    "t218": "Giáo trình",
    "t219": " 42 trò chơi giúp trẻ hay nói (Tập 2)",
    "t220": "Hình thức",
    "t221": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t222": "Hỏi lịch & học phí →",
    "t223": "Cấp 3",
    "t224": "Chơi cùng giác quan — Giác quan, hành vi, ngôn ngữ",
    "t225": "“Cháu lười nói.” Thực tế có thể là một trẻ đang khó khăn về cảm giác. Cấp này dành cho nhóm trẻ khó nhất: né tránh, quá tải, tìm kiếm cảm giác liên tục, kén ăn, sợ bẩn, né chạm…",
    "t226": "Nội dung chi tiết",
    "t227": "Hiểu sâu về tám hệ giác quan",
    "t228": "Đọc ngưỡng giác quan, phân biệt bốn nhóm phản ứng",
    "t229": "Nhận biết: giác quan nào đang cản trở đứa trẻ này có ngôn ngữ",
    "t230": "Hệ thống bài tập theo từng hệ giác quan",
    "t231": "Biến mọi không gian thành nơi trị liệu",
    "t232": "Chế độ cảm giác – ngôn ngữ",
    "t233": "Giải mẫn cảm",
    "t234": "Học xong có năng lực",
    "t235": "Lên được chế độ cảm giác – ngôn ngữ và triển khai sử dụng hoạt động chơi để cân bằng cảm giác và mở rộng ngôn ngữ.",
    "t236": "Điều kiện",
    "t237": " Đã học Cấp 2",
    "t238": "Giáo trình",
    "t239": " Lên tiếng (Tập 3)",
    "t240": "Hình thức",
    "t241": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t242": "Hỏi lịch & học phí →",
    "t243": "M",
    "t244": "MIỆNG XINH LỜI HAY",
    "t245": "TS.BS. Nguyễn Hoàng Oanh · TS. Nguyễn Thị Phương",
    "t246": "Cành thứ hai. Từ phân tích được lỗi phát âm cho tới xúc chạm được vào cơ thể để tạo lời nói cho trẻ. Đây là hệ có bộ giáo trình bốn tập và bộ công cụ riêng.",
    "t247": "Hoàn thành trọn hệ →",
    "t248": " Trị liệu viên Tài năng — hệ Kích tạo âm chuẩn y khoa",
    "t249": "Cấp 1",
    "t250": "Cấu âm — Xác định đúng lỗi & huấn luyện",
    "t251": "Trẻ này ngọng kiểu gì — và tập âm đó thế nào cho đúng? Cấp này dạy nhìn đúng cơ chế tạo ra lỗi, từ đó huấn luyện cách tạo âm chính xác.",
    "t252": "Nội dung chi tiết",
    "t253": "Phân loại rối loạn âm lời nói",
    "t254": "Giải phẫu cơ quan phát âm · khám cơ quan phát âm (OMA)",
    "t255": "Ngữ âm học tiếng Việt · mô hình ngữ âm",
    "t256": "Quy trình lượng giá",
    "t257": "Phân tích phiên âm trên ca thật",
    "t258": "Kỹ thuật huấn luyện cấu âm sáu giai đoạn",
    "t259": "Trò chơi và hoạt động phát âm",
    "t260": "Học xong có năng lực",
    "t261": "Tiến hành thu thập hồ sơ và thực hiện trọn vẹn buổi lượng giá phát âm, lên kế hoạch huấn luyện phát âm và triển khai thành công các tiết tập phát âm cho trẻ.",
    "t262": "Điều kiện",
    "t263": " Đã học Âm ngữ trị liệu Bậc 1",
    "t264": "Giáo trình",
    "t265": " Miệng xinh lời hay — Tập 1 Cấu âm",
    "t266": "Hình thức",
    "t267": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t268": "Hỏi lịch & học phí →",
    "t269": "Cấp 2",
    "t270": "Âm vị — Cài đặt lại hệ thống",
    "t271": "Dành cho câu hỏi “vì sao chỉnh mãi một âm mà không xong” — vì lỗi nằm ở hệ thống ghi nhận âm vị, không ở riêng lẻ từng âm.",
    "t272": "Nội dung chi tiết",
    "t273": "Đọc hệ thống chỉ số phát âm · phân phối âm · quy trình bệnh lý",
    "t274": "Lựa chọn qui trình âm vị đích",
    "t275": "Các liệu pháp âm vị",
    "t276": "Quá trình phát triển âm vị và các hoạt động phát triển âm vị",
    "t277": "Kế hoạch trị liệu",
    "t278": "Xây dựng hệ thống bài tập âm vị cá nhân hoá",
    "t279": "Học xong có năng lực",
    "t280": "Có khả năng tạo lập hồ sơ phân tích âm vị hệ thống và kế hoạch trị liệu thành công cho trẻ của bạn.",
    "t281": "Điều kiện",
    "t282": " Đã học Cấp 1",
    "t283": "Giáo trình",
    "t284": " Miệng xinh lời hay — Tập 2 Can thiệp âm vị",
    "t285": "Hình thức",
    "t286": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t287": "Hỏi lịch & học phí →",
    "t288": "Cấp 3",
    "t289": "Bàn tay kì diệu — Bản đồ giải phẫu phát âm",
    "t290": "Trẻ ít tập trung giao tiếp, giảm bắt chước, khó khăn trong tự kiểm soát giác quan và vận động phát âm — bạn làm mẫu nhiều lần nhưng trẻ vẫn không tạo được âm chính xác.",
    "t291": "Nội dung chi tiết",
    "t292": "Cơ chế vận động phát âm và các khó khăn thường gặp ở trẻ",
    "t293": "Triết lý và giải phẫu nền của kỹ thuật xúc giác vận động phát âm",
    "t294": "Bản đồ giải phẫu phát âm · kỹ thuật kích tạo",
    "t295": "Chỉ định và chống chỉ định · đạo đức can thiệp",
    "t296": "Tích hợp với các kỹ thuật khác",
    "t297": "Học xong có năng lực",
    "t298": "Bản đồ kích âm cho toàn bộ hệ thống âm tiếng Việt · hồ sơ phân tích toàn bộ 7 cấp bậc phát âm · thực hiện kích tạo âm chính xác, nhẹ nhàng và vui vẻ.",
    "t299": "Điều kiện",
    "t300": " Đã học Cấp 2",
    "t301": "Giáo trình",
    "t302": " Miệng xinh lời hay — Tập 3 Bản đồ giải phẫu phát âm",
    "t303": "Hình thức",
    "t304": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t305": "Hỏi lịch & học phí →",
    "t306": "Cấp 4",
    "t307": "Trẻ nói khó và đồng mắc — Kích âm nâng cao",
    "t308": "Trẻ hiểu, muốn nói, mà miệng không làm theo được — hoặc trẻ kém chú ý nhưng đôi khi muốn nói. Thường không chỉ mắc một rối loạn. Đây là cấp khó nhất của hệ, dành cho trẻ nói khó kèm theo rối loạn khác đi cùng, cũng là chỗ hai cành gặp lại thân cây.",
    "t309": "Nội dung chi tiết",
    "t310": "Tháp vận động lời nói MSH bảy bậc · biểu mẫu SAO",
    "t311": "Bốn bước thiết kế mục tiêu vận động lời nói",
    "t312": "Nhận diện trẻ đồng mắc và trẻ đa rối loạn",
    "t313": "Xây dựng chương trình kết hợp tạo âm và giao tiếp chức năng",
    "t314": "Tích hợp tạo âm với các phương pháp khác",
    "t315": "Liên liệu pháp — phối hợp với hoạt động trị liệu và vật lý trị liệu",
    "t316": "Học xong có năng lực",
    "t317": "Xử lý được những ca nặng nhất và khó nhất về phát âm ở trẻ nhỏ.",
    "t318": "Vì sao chặn ở đây:",
    "t319": " Đây là điều kiện bắt buộc, không phải khuyến nghị. Trẻ đa rối loạn thì lời nói chỉ là một mắt xích — không có nền giao tiếp chức năng, bạn sẽ chỉ có thể ép trẻ tạo âm chứ không khiến trẻ hào hứng và khao khát tự nói ra rõ ràng.",
    "t320": "Điều kiện",
    "t321": " Đã học Cấp 3 ",
    "t322": "và",
    "t323": " Âm ngữ trị liệu Bậc 1, Bậc 2",
    "t324": "Giáo trình",
    "t325": " Kích âm nâng cao",
    "t326": "Hình thức",
    "t327": " Online tự học (nếu có) + 1–2 ngày trực tiếp, tuỳ nội dung",
    "t328": "Hỏi lịch & học phí →",
    "t329": "★",
    "t330": "Đỉnh — Can thiệp đa trường phái",
    "t331": "TS.BS. Nguyễn Hoàng Oanh",
    "t332": "Tích hợp các công cụ và phương pháp trên cùng một đứa trẻ. Dành cho người đã có nền và cần cầm ca đa rối loạn — nơi không một trường phái đơn lẻ nào đủ.",
    "t333": "Điều kiện vào học:",
    "t334": " đã hoàn thành ",
    "t335": "Âm ngữ trị liệu ba bậc",
    "t336": " và trọn ",
    "t337": "ít nhất một chuyên khoa",
    "t338": " (Chơi lớn hoặc Miệng xinh lời hay). Đây là chặng cuối để đạt danh hiệu ",
    "t339": "Trị liệu viên Tinh hoa Dr Owl",
    "t340": ".",
    "t341": "Hành vi ngôn ngữ",
    "t342": "Nguyên tắc cơ bản của hành vi ngôn ngữ và vai trò trong can thiệp cho trẻ tự kỷ",
    "t343": "Phối hợp phương pháp hành vi với chiến lược phát triển trong can thiệp giao tiếp",
    "t344": "Xây dựng giao tiếp lời nói chức năng, phù hợp nhu cầu và khả năng của trẻ",
    "t345": "Ngôn ngữ tư duy và suy đoán tâm trí",
    "t346": "Tháp tâm trí theo tuổi · các cấp độ thấu hiểu theo hướng tiếp cận phát triển",
    "t347": "Hoạt động giúp trẻ nhận biết cảm xúc, suy nghĩ và góc nhìn của người khác",
    "t348": "Phát triển kỹ năng hội thoại, kể chuyện và diễn đạt trong tương tác xã hội",
    "t349": "Can thiệp sớm + PROMPT",
    "t350": "Phối hợp chương trình can thiệp sớm với phương pháp PROMPT",
    "t351": "Hỗ trợ phát triển giao tiếp, lời nói và tương tác ở trẻ nhỏ",
    "t352": "Vui chơi có cấu trúc kết hợp kỹ thuật y khoa trong can thiệp",
    "t353": "Tích hợp giác quan – vận động vào kế hoạch",
    "t354": "Đưa mục tiêu giác quan vào cùng một chương trình với ngôn ngữ, lời nói và hành vi",
    "t355": "Cân bằng liều lượng giữa các mục tiêu để kế hoạch chạy được trong một tuần thật",
    "t356": "Làm việc liên liệu pháp với hoạt động trị liệu và vật lý trị liệu",
    "t357": "Hỏi về khoá đỉnh",
    "t358": "Chứng nhận",
    "t359": "Bạn nhận được gì trên giấy",
    "t360": "📜",
    "t361": "Chứng nhận hoàn thành",
    "t362": "Hoàn thành từng bậc, từng cấp đều có chứng nhận riêng — ghi rõ nội dung đã học và sản phẩm đã làm trên ca thật.",
    "t363": "🎖",
    "t364": "Trị liệu viên Tài năng",
    "t365": "Hoàn thành trọn một hệ: hệ Âm ngữ trị liệu · hệ Trị liệu ứng dụng Chơi · hệ Kích tạo âm chuẩn y khoa.",
    "t366": "🏆",
    "t367": "Trị liệu viên Toàn năng Dr Owl",
    "t368": "Đi hết Âm ngữ trị liệu ba bậc và trọn ít nhất một chuyên khoa.",
    "t369": "⭐",
    "t370": "Trị liệu viên Tinh hoa",
    "t371": "Danh hiệu cao nhất. Toàn năng cộng thêm khoá đỉnh Can thiệp đa trường phái.",
    "t372": "Cách học",
    "t373": "Không dừng ở bài giảng",
    "t374": "Học xong mà vào buổi trị liệu vẫn lúng túng là vì chưa ai xem bạn làm. Mô hình của chúng tôi có bốn lớp.",
    "t375": "Bài giảng thu sẵn — học trên web",
    "t376": "Xem lại bao nhiêu lần cũng được, học theo tốc độ của mình. Phần lý thuyết và quy trình nằm ở đây.",
    "t377": "Buổi Zoom cùng giảng viên",
    "t378": "Thảo luận lâm sàng, phân tích case, chỉnh sửa thực hành. Bạn mang ca của mình lên — không phải ca giả định trong sách.",
    "t379": "Một đến hai ngày thực hành trực tiếp",
    "t380": "Trạm thực hành, làm trên trẻ thật hoặc trên clip ca thật, có người đứng cạnh sửa tay và sửa lời cho bạn.",
    "t381": "Thực hành lâm sàng có giám sát",
    "t382": "Sau khi xong Âm ngữ trị liệu ba bậc, bạn có thể đăng ký để được giám sát trên ca thật của chính mình — tại OWLSPEAKS hoặc tại cơ sở của bạn. ",
    "t383": "Xem phần chuyển giao & giám sát →",
    "t384": "Nhắn một câu về ca bạn đang vướng",
    "t385": "Chúng tôi sẽ chỉ đúng cấp cần học — và nói thẳng cấp nào chưa cần với bạn lúc này. Lịch khai giảng cập nhật sớm nhất ở nhóm Zalo.",
    "t386": "Nhắn Zalo 0866620583",
    "t387": "Vào nhóm Zalo lịch khai giảng"
  },
  "images": {},
  "links": {
    "link001": "#lop-cha-me/p1",
    "link002": "#lop-cha-me/p2",
    "link003": "#dao-tao/dinh",
    "link004": "#dao-tao/choi",
    "link005": "#dao-tao/mxlh",
    "link006": "#dao-tao/ancs-3",
    "link007": "#dao-tao/ancs-2",
    "link008": "#dao-tao/ancs-1",
    "link009": "#chuyen-giao",
    "link010": "#dao-tao/chi-tiet",
    "link011": "#dao-tao/ancs-1",
    "link012": "#dao-tao/ancs-2",
    "link013": "#dao-tao/choi-1",
    "link014": "#dao-tao/choi-3",
    "link015": "#dao-tao/mxlh-1",
    "link016": "#dao-tao/mxlh-3",
    "link017": "https://tinyurl.com/thamgiaDrOwlAcademy",
    "link018": "https://zalo.me/0866620583",
    "link019": "https://zalo.me/0866620583",
    "link020": "https://zalo.me/0866620583",
    "link021": "https://zalo.me/0866620583",
    "link022": "https://zalo.me/0866620583",
    "link023": "https://zalo.me/0866620583",
    "link024": "https://zalo.me/0866620583",
    "link025": "https://zalo.me/0866620583",
    "link026": "https://zalo.me/0866620583",
    "link027": "https://zalo.me/0866620583",
    "link028": "https://zalo.me/0866620583",
    "link029": "#chuyen-giao",
    "link030": "https://zalo.me/0866620583",
    "link031": "https://tinyurl.com/thamgiaDrOwlAcademy"
  },
  "alts": {},
  "placeholders": {}
};
