import { ParentPageData } from "./ParentPage.types";

export const parentPageMockData: ParentPageData = {
  "texts": {
    "t001": "Dành cho cha mẹ",
    "t002": "Điều bạn lo lắng ở con?",
    "t003": "điều gì đó.",
    "t004": 'Con bạn chậm nói, ít nhìn mắt, ít chịu chơi cùng, chạy nhảy không ngừng, khó phát âm... đó không phải do con "lười nói" cũng không thể "lớn rồi sẽ hết". Thực sự thì những biểu hiện đó cho thấy con đang cố "nói" cho chúng ta biết: con cần hỗ trợ!',
    "t005": "Làm 4 bài test nhanh cho con — miễn phí",
    "t006": "Đăng ký khám cho con",
    "t007": "Khi nào nên cho con đi khám?",
    "t008": "Nếu con bạn có từ hai dấu hiệu trở lên dưới đây, đừng chờ thêm. Can thiệp sớm vài tháng có thể thay đổi cả cuộc đời.",
    "t009": "12 tháng chưa bập bẹ, chưa chỉ tay, chưa vẫy tay chào",
    "t010": "18 tháng chưa nói được từ đơn có nghĩa",
    "t011": "24 tháng chưa ghép được hai từ",
    "t012": "Gọi tên không quay lại, dù nghe tốt",
    "t013": "Nói được nhưng người lạ không hiểu con nói gì",
    "t014": "Chơi lặp đi lặp lại một kiểu, không chơi giả vờ",
    "t015": "Không chịu chơi cùng, không luân phiên, không bắt chước",
    "t016": "Kén ăn nặng, sợ bẩn, né chạm, che tai với tiếng động",
    "t017": "Chạy nhảy không ngừng hoặc quá thụ động",
    "t018": "Con từng nói được rồi mất dần",
    "t019": "Đọc sâu hơn theo đúng điều bạn đang lo:",
    "t020": "Con chậm nói — có nên chờ thêm không? →",
    "t021": "Các chủ đề khác (nghi ngờ tự kỷ · nói ngọng · khe hở môi vòm · kén ăn và giác quan · từng nói rồi mất từ) sẽ lần lượt được bổ sung.",
    "t022": "Một lưu ý thẳng thắn:",
    "t023": " danh sách này để bạn quyết định có đi khám hay không — không phải để tự chẩn đoán cho con. Chỉ một buổi lượng giá đầy đủ mới trả lời được con đang ở đâu.",
    "t024": "Việc thứ nhất",
    "t025": "Đăng ký khám & lượng giá cho con",
    "t026": "Một buổi lượng giá không phải là “bác sĩ nhìn con vài phút rồi kết luận”. Đây là quy trình có công cụ, có số liệu, và kết thúc bằng số đo phát triển của con kèm chương trình hỗ trợ.",
    "t027": "Bạn kể, chúng tôi hỏi",
    "t028": "Bệnh sử, mốc phát triển, thói quen sinh hoạt, điều bạn lo nhất… Phần này quan trọng ngang phần khám, vì bạn là người biết con rõ nhất.",
    "t029": "Quan sát và lấy mẫu",
    "t030": "Quan sát con chơi, tương tác, phát âm… Lấy mẫu ngôn ngữ, khám cơ quan phát âm, sàng lọc giác quan và vận động. Có quay hình nếu bạn đồng ý, để phân tích lại.",
    "t031": "Phân tích bằng công cụ chuẩn hoá",
    "t032": "Đối chiếu với thang phát triển và các bộ công cụ chuẩn hoá — để trả lời được con đang ở đâu bằng con số, không phải bằng cảm nhận.",
    "t033": "Bạn cầm về một báo cáo số đo phát triển và kế hoạch “tác chiến”",
    "t034": "Báo cáo lượng giá, mục tiêu ưu tiên trong 3 tháng tới, và những việc bạn làm được ngay tại nhà. Nếu con cần chuyên khoa khác, chúng tôi sẽ tư vấn.",
    "t035": "Đặt lịch khám, tư vấn qua Zalo",
    "t036": "Gọi 0866620583",
    "t037": "Việc thứ hai",
    "t038": "Can thiệp cho con tại OWLSPEAKS",
    "t039": "Con được gì",
    "t040": "Chương trình ",
    "t041": "may đo theo kết quả lượng giá",
    "t042": ", không phải giáo án dùng chung",
    "t043": "Mục tiêu viết ra được, đo được, có mốc kiểm tra lại",
    "t044": "Tích hợp giác quan — vận động — chơi — ngôn ngữ — lời nói trong cùng một kế hoạch",
    "t045": "Trị liệu viên được đào tạo theo cùng một chuẩn của Dr Owl Academy",
    "t046": "Giám sát chuyên môn liên tục bởi TS.BS. Nguyễn Hoàng Oanh",
    "t047": "Bạn được gì",
    "t048": "Biết chính xác buổi hôm nay con làm gì và vì sao",
    "t049": "Được hướng dẫn mang mục tiêu về nhà — lồng vào bữa ăn, tắm, đi chợ, giờ ngủ…",
    "t050": "Dự giờ định kì để học hỏi và trao đổi với chuyên viên",
    "t051": "Nhận báo cáo tiến bộ định kỳ, có số liệu so với lúc bắt đầu",
    "t052": "Nguyên tắc của chúng tôi:",
    "t053": " cha mẹ là người can thiệp nhiều giờ nhất trong tuần, không phải trị liệu viên. Vì vậy mọi kế hoạch đều có phần dành cho bạn.",
    "t054": "Hỏi về can thiệp",
    "t055": "Việc thứ ba",
    "t056": "Học để tự dạy con",
    "t057": "Cha mẹ là người thầy tốt nhất của con. Chúng tôi có hai mức để bạn chọn — từ một ngày cho tới tám tuần được kèm riêng.",
    "t058": "Phổ biến nhất",
    "t059": "Lớp cha mẹ — một ngày (B247)",
    "t060": "Không cần nền tảng. Hiểu về con, mang về cẩm nang hướng dẫn cha mẹ, bảng kiểm kỹ năng đã chấm cho con bạn, và những hoạt động làm được ngay tối nay.",
    "t061": "999.999đ",
    "t062": "Xem lớp một ngày",
    "t063": "Cầm tay chỉ việc",
    "t064": "Dạy con 24/7 — coaching 1–1 (P247)",
    "t065": "Tám tuần online, mỗi tuần một buổi Zoom riêng và clip bạn quay ở nhà theo kế hoạch được hướng dẫn, để trainer xem và sửa — điều mà sách và lớp nhóm không thể mang lại được.",
    "t066": "Học phí: liên hệ",
    "t067": "Số suất mỗi đợt có hạn",
    "t068": "Xem khoá coaching",
    "t069": "Xem chi tiết hai lớp →",
    "t070": "Việc thứ tư",
    "t071": "Ba cuốn nên đọc trước",
    "t072": "Nếu bạn chỉ mua một cuốn, hãy bắt đầu bằng cuốn hợp với tuổi và tình trạng của con.",
    "t073": "0–5 tuổi · theo dõi",
    "t074": "“Bản đồ” 5 năm đầu đời của con",
    "t075": "Checklist phát triển theo từng giai đoạn, phần ghi dấu mốc của con, và các dấu hiệu “cờ đỏ” để phát hiện sớm.",
    "t076": "199.000đ",
    "t077": "Đặt sách",
    "t078": "Tự kỷ · can thiệp tại nhà",
    "t079": "Dạy con 24/7",
    "t080": "Hiểu đúng về tự kỷ, chọn mục tiêu cá nhân hoá, kèm bảng kiểm và mẫu kế hoạch dạy con tại nhà.",
    "t081": "380.000đ",
    "t082": "Đặt sách",
    "t083": "Phát triển · vốn từ",
    "t084": "100 từ đầu tiên của bé",
    "t085": "100 từ trẻ Việt hiểu và nói sớm nhất, thống kê từ 600 trẻ ba miền. Dạy từ nào trước, dạy thế nào.",
    "t086": "245.000đ",
    "t087": "Đặt sách",
    "t088": "Xem cả 7 cuốn →",
    "t089": "Câu hỏi cha mẹ hay hỏi",
    "t090": "Con tôi mới 18 tháng, đi khám có sớm quá không?",
    "t091": "Không sớm. Ngược lại, đây là khoảng thời gian can thiệp cho kết quả tốt nhất. Nếu con phát triển bình thường, bạn ra về nhẹ nhõm và có một bản đồ theo dõi. Nếu có vấn đề, bạn bắt đầu sớm hơn được vài tháng — và vài tháng ở tuổi này rất đáng giá.",
    "t092": "Ông bà bảo “lớn rồi sẽ nói”, có đúng không?",
    "t093": "Một số trẻ đúng là nói muộn rồi bắt kịp. Nhưng không có cách nào biết con bạn thuộc nhóm nào nếu không lượng giá. Rủi ro của việc chờ đợi lớn hơn nhiều so với chi phí của một buổi khám.",
    "t094": "Tôi ở tỉnh xa, có học và theo dõi từ xa được không?",
    "t095": "Được. Khoá coaching ",
    "t096": "Dạy con 24/7",
    "t097": " hoàn toàn online. Các khoá đào tạo có phần bài giảng thu sẵn học trên web, chỉ phần thực hành mới cần có mặt — thường gói trong 1–2 ngày.",
    "t098": "Học phí và lịch khai giảng thế nào?",
    "t099": "Học phí thay đổi theo cấp và hình thức học. Bạn nhắn Zalo ",
    "t100": "0866620583",
    "t101": " hoặc tham gia ",
    "t102": "nhóm Zalo cập nhật lịch",
    "t103": " để nhận thông tin mới nhất.",
    "t104": "Sách mua ở đâu, có giao tận nơi không?",
    "t105": "Bạn đặt trực tiếp qua Zalo ",
    "t106": "0866620583",
    "t107": ". Xem giá và nội dung từng cuốn ở ",
    "t108": "trang Sách & học liệu",
    "t109": ".",
    "t110": "Kể cho chúng tôi nghe về con bạn",
    "t111": "Một tin nhắn ngắn cũng đủ để chúng tôi nói cho bạn biết nên bắt đầu từ đâu — khám, học, hay chỉ cần một cuốn sách.",
    "t112": "Nhắn Zalo 0866620583",
    "t113": "Gọi ngay"
  },
  "images": {
    "img001": "/images/buoi-kham-va-luong-gia-cho-tre-c8dc87e7.jpg",
    "img002": "/images/ban-o-5-nam-au-oi-cua-con-763c4a96.jpg",
    "img003": "/images/day-con-24-7-0c3aad87.jpg",
    "img004": "/images/100-tu-au-tien-cua-be-532c8917.jpg"
  },
  "links": {
    "link001": "#phu-huynh/test-nhanh",
    "link002": "https://zalo.me/0857389318",
    "link003": "#phu-huynh/cham-noi",
    "link004": "https://zalo.me/0857389318",
    "link005": "tel:0866620583",
    "link006": "https://zalo.me/0857389318",
    "link007": "#lop-cha-me/p1",
    "link008": "#lop-cha-me/p2",
    "link009": "#lop-cha-me",
    "link010": "https://zalo.me/0866620583",
    "link011": "https://zalo.me/0866620583",
    "link012": "https://zalo.me/0866620583",
    "link013": "#sach",
    "link014": "https://tinyurl.com/thamgiaDrOwlAcademy",
    "link015": "#sach",
    "link016": "https://zalo.me/0866620583",
    "link017": "tel:0866620583"
  },
  "alts": {
    "alt001": "Buổi khám và lượng giá cho trẻ",
    "alt002": "Bản đồ 5 năm đầu đời của con",
    "alt003": "Dạy con 24/7",
    "alt004": "100 từ đầu tiên của bé"
  },
  "placeholders": {}
};
