import { BooksPageData } from "./BooksPage.types";

export const booksPageMockData: BooksPageData = {
  "texts": {
    "t001": "Sách & học liệu",
    "t002": "Trẻ em Việt Nam vui chơi, phát triển và giao tiếp bằng tiếng Việt.",
    "t003": "phát triển và giao tiếp bằng tiếng Việt.",
    "t004": "Chắt lọc từ kiến thức và kinh nghiệm lâm sàng của 12 năm xây dựng ngành Ngôn ngữ trị liệu, đây là những cuốn sách và giáo trình chuyên khoa viết riêng cho PH và GV dùng để dạy trẻ em Việt Nam - nói rõ, nói hay và chủ động giao tiếp, hòa nhập bền vững.",
    "t005": "Cha mẹ · Tự kỷ",
    "t006": "Dạy con 24/7",
    "t007": "Giúp cha mẹ hiểu đúng về tự kỷ, can thiệp lấy gia đình làm trọng tâm, đánh giá và chọn mục tiêu cá nhân hoá. Kèm bảng kiểm và mẫu kế hoạch dạy con tại nhà dựa trên khoa học, dễ áp dụng.",
    "t008": "380.000đ",
    "t009": "Đặt sách qua Zalo",

    "t010": "Chuyên viên · Cha mẹ học sâu",
    "t011": "“29 giọng nói” — Hơn cả bật âm",
    "t012": "Hiểu sâu cách trẻ tiếp thu thế giới và hình thành giao tiếp. Cung cấp hàng chục phương pháp và công cụ can thiệp ngôn ngữ cụ thể, hiệu quả, dễ áp dụng.",
    "t013": "386.000đ",
    "t014": "Đặt sách qua Zalo",
    
    "t015": "Giác quan · Hành vi · Ngôn ngữ",
    "t016": "Lên tiếng",
    "t017": "Cẩm nang thực hành giúp cha mẹ, giáo viên và chuyên viên hiểu đúng hệ thống giác quan, sàng lọc sớm khó khăn và “kê đơn giác quan — bốc thuốc ngôn ngữ” qua thiết kế hoạt động sinh hoạt hằng ngày, nhằm điều hoà cảm giác, hỗ trợ hành vi và phát triển giao tiếp lời nói tự nhiên, bền vững.",
    "t018": "399.000đ",
    "t019": "Đặt sách qua Zalo",

    "t020": "Chơi · Phát triển",
    "t021": "Chơi lớn",
    "t022": "Vai trò của chơi và mối liên hệ giữa chơi với ngôn ngữ. Kèm bảng kiểm phát triển, quy trình dạy kỹ năng, cách tương tác — chơi với trẻ kể cả trẻ có rào cản phát triển, gợi ý hoạt động chơi, lồng ghép chơi trong sinh hoạt và dùng chơi để dạy các kỹ năng khác.",
    "t023": "326.000đ",
    "t024": "Đặt sách qua Zalo",

    "t025": "Chậm nói · Vốn từ",
    "t026": "100 từ đầu tiên của bé",
    "t027": "Tổng hợp 100 từ trẻ HIỂU và NÓI được sớm nhất, nghiên cứu và thống kê từ 600 trẻ em Việt Nam ở cả ba miền. Giới thiệu lộ trình phát triển từ vựng theo từng giai đoạn, chia rõ bốn nhóm từ quan trọng — danh từ, động từ, từ cốt lõi, từ khái niệm — kèm hướng dẫn cụ thể cách phát triển từng nhóm.",
    "t028": "245.000đ",
    "t029": "Đặt sách qua Zalo",

    "t030": "Chơi để nói",
    "t031": "42 trò chơi giúp trẻ hay nói",
    "t032": "Nhận diện trẻ đang ở giai đoạn phát triển nào, đọc hiểu trẻ từ những hành vi mơ hồ, thiết kế hoạt động chơi phù hợp với năng lực hiện tại. Từng trò chơi được thiết kế chi tiết: bạn nói gì, làm gì, dùng gì.",
    "t033": "288.000đ",
    "t034": "Đặt sách qua Zalo",

    "t035": "Cha mẹ · 0–5 tuổi",
    "t036": "“Bản đồ” 5 năm đầu đời của con",
    "t037": "Cẩm nang giúp cha mẹ hiểu từng bước trưởng thành của trẻ 0–5 tuổi: theo dõi vận động, ngôn ngữ, nhận thức và kỹ năng xã hội; checklist phát triển cụ thể; phần ghi lại dấu mốc của con; và những dấu hiệu “cờ đỏ” của rối loạn phổ tự kỷ để phát hiện sớm.",
    "t038": "199.000đ",
    "t039": "Đặt sách qua Zalo",

    "t040": "Giá bìa cập nhật đến 08/2026. Đặt sách qua Zalo ",
    "t041": "0866620583",
    "t042": " — nhắn tên sách và số lượng, chúng tôi báo phí giao và thời gian nhận.",
    "t043": "Bộ công cụ đi kèm khoá học",
    "t044": "Không bán lẻ",
    "t045": "Bộ công cụ Miệng xinh lời hay",
    "t046": "Cung cấp kiến thức nền tảng về âm lời nói, hướng dẫn lượng giá rối loạn phát âm và thực hành từng âm tiếng Việt — giúp can thiệp ngôn ngữ khoa học, có hệ thống, dễ áp dụng. Bao gồm toàn bộ bài tập cho các cấp độ huấn luyện phát âm, huấn luyện âm vị và sử dụng vui chơi để trị liệu lời nói. Trong bộ có: sách hướng dẫn thực hành phát âm (bản thường và bản lò xo), bộ tranh lượng giá phát âm tiếng Việt, Miệng xinh lời hay Tập 2, bộ thẻ cặp tương phản phát âm, và Giải phẫu phát âm — cả bộ kèm biểu mẫu lượng giá, hồ sơ và kế hoạch can thiệp.",
    "t047": "Tài liệu học tập đi kèm khoá học, được biên soạn nhằm hỗ trợ học viên thực hành và áp dụng kiến thức hiệu quả. Chỉ dành cho học viên đã đăng ký khoá học.",
    "t048": "Xem hệ Miệng xinh lời hay",
    "t049": "Nên đọc cuốn nào trước?",
    "t050": "Con 0–5 tuổi, tôi muốn theo dõi",
    "t051": "Bắt đầu bằng ",
    "t052": "“Bản đồ” 5 năm đầu đời của con",
    "t053": ". Nếu thấy dấu hiệu cờ đỏ, đọc tiếp ",
    "t054": "Dạy con 24/7",
    "t055": ".",
    "t056": "Con chậm nói",
    "t057": "100 từ đầu tiên của bé",
    "t058": " để biết dạy từ nào trước, rồi ",
    "t059": "42 trò chơi giúp trẻ hay nói",
    "t060": " để biết dạy bằng cách nào.",
    "t061": "Con kén ăn, sợ bẩn, né chạm",
    "t062": "Lên tiếng",
    "t063": " — cuốn duy nhất nối được giác quan với hành vi và ngôn ngữ trong cùng một cẩm nang.",
    "t064": "Tôi là giáo viên / trị liệu viên",
    "t065": "“29 giọng nói”",
    "t066": " và ",
    "t067": "Chơi lớn",
    "t068": " là hai cuốn nền. Sau đó vào tháp đào tạo để có bộ công cụ.",
    "t069": "Tôi phụ trách chuyên môn ở trung tâm",
    "t070": "Mua cả bộ cho đội, rồi chuẩn hoá bằng ",
    "t071": "gói chuyển giao",
    "t072": " để cả trung tâm dùng chung một chuẩn.",
    "t073": "Tôi muốn tặng quà cho cha mẹ mới",
    "t074": "“Bản đồ” 5 năm đầu đời của con",
    "t075": " — có phần “note” để ba mẹ lưu lại dấu mốc của con.",
    "t076": "Để đặt sách, bạn hãy nhấn nút ĐẶT SÁCH. Nếu bạn phân vân chọn lựa, hãy nhấn nút tư vấn thêm",
    "t077": "Nhắn tên sách và số lượng qua Zalo. Nếu bạn phân vân giữa hai cuốn, kể cho chúng tôi nghe về con bạn — chúng tôi sẽ nói cuốn nào hợp hơn.",
    "t078": "Đặt sách",
    "t079": "Tư vấn thêm qua Zalo"
  },
  "images": {
    "img001": "/images/day-con-24-7-0c3aad87.jpg",
    "img002": "/images/29-giong-noi-hon-ca-bat-am-c5f9072d.jpg",
    "img003": "/images/len-tieng-e5f17cd6.jpg",
    "img004": "/images/choi-lon-06fe4255.jpg",
    "img005": "/images/100-tu-au-tien-cua-be-532c8917.jpg",
    "img006": "/images/42-tro-choi-giup-tre-hay-noi-13aeaa3c.jpg",
    "img007": "/images/ban-o-5-nam-au-oi-cua-con-763c4a96.jpg",
    "img008": "/images/bo-sach-va-cong-cu-dr-owl-academy-8a477b90.jpg",
    "img009": "/images/mieng-xinh-loi-hay-tap-2-va-bo-the-cap-tuong-pha-6c08ca75.jpg",
    "img010": "/images/giai-phau-phat-am-va-huong-dan-kich-am-co-so-abd6ac77.jpg"
  },
  "links": {
    "link001": "https://zalo.me/0866620583",
    "link002": "https://zalo.me/0866620583",
    "link003": "https://zalo.me/0866620583",
    "link004": "https://zalo.me/0866620583",
    "link005": "https://zalo.me/0866620583",
    "link006": "https://zalo.me/0866620583",
    "link007": "https://zalo.me/0866620583",
    "link008": "#dao-tao/mxlh",
    "link009": "#chuyen-giao",
    "link010": "https://zalo.me/0866620583",
    // "link011": "tel:0866620583"
    "link011": "https://docs.google.com/forms/d/e/1FAIpQLScCQJEBuiUfjCbUBWEHFuhP5i_kFfQThpzQ3psLKDrBK55iEQ/viewform"
  },
  "alts": {
    "alt001": "Dạy con 24/7",
    "alt002": "“29 giọng nói” — Hơn cả bật âm",
    "alt003": "Lên tiếng",
    "alt004": "Chơi lớn",
    "alt005": "100 từ đầu tiên của bé",
    "alt006": "42 trò chơi giúp trẻ hay nói",
    "alt007": "“Bản đồ” 5 năm đầu đời của con",
    "alt008": "Sách hướng dẫn thực hành phát âm và bộ tranh lượng giá",
    "alt009": "Miệng xinh lời hay Tập 2 và bộ thẻ cặp tương phản phát âm",
    "alt010": "Giải phẫu phát âm và Hướng dẫn kích âm cơ sở"
  },
  "placeholders": {}
};
