import { TransferPageData } from "./TransferPage.types";

export const transferPageMockData: TransferPageData = {
  "texts": {
    "t001": "Chuyển giao & giám sát",
    "t002": "Học xong là một chuyện.",
    "t003": "Làm đúng là chuyện khác.",
    "t004": "Khoá học cho bạn quy trình. Nhưng chỉ khi có người xem bạn làm trên ca thật và nói “chỗ này chưa đúng” thì quy trình mới thành nghề. Đó là việc của phần này.",
    "t005": "Đặt buổi trao đổi",
    "t006": "Xem chương trình đào tạo",
    "t007": "Bốn hạng mục, tính phí riêng từng mức",
    "t008": "Bạn lấy đúng phần mình cần, không phải mua trọn gói. Cá nhân thường bắt đầu từ hạng mục thứ nhất; cơ sở can thiệp thường lấy cả bốn.",
    "t009": "👁",
    "t010": "Thực hành lâm sàng có giám sát",
    "t011": "Lõi của gói chuyển giao. Bạn làm việc trên ca thật của chính mình, có TS.BS. Nguyễn Hoàng Oanh ngồi cạnh hoặc xem lại và sửa cho bạn.",
    "t012": "Gói ",
    "t013": "4 buổi",
    "t014": " — đủ để đi hết một ca từ lượng giá đến kế hoạch và triển khai can thiệp",
    "t015": "Gói ",
    "t016": "8 buổi",
    "t017": " — theo bạn qua nhiều ca",
    "t018": "Tại ",
    "t019": "OWLSPEAKS",
    "t020": ": bạn mang trẻ đến, thực hành ngay trong phòng can thiệp",
    "t021": "Tại ",
    "t022": "cơ sở của bạn",
    "t023": ": BS Cú có thể đến tận nơi, hoặc bạn quay clip buổi trị liệu rồi cùng xem và sửa qua Zoom — hai hình thức tính phí khác nhau",
    "t024": "Điều kiện:",
    "t025": " Đã hoàn thành Âm ngữ trị liệu ba bậc",
    "t026": "📄",
    "t027": "Quyền sử dụng giáo trình & bộ biểu mẫu",
    "t028": "Cơ sở được dùng chính bộ công cụ mà Dr Owl Academy đang dùng trong vận hành hằng ngày, thay vì mỗi người tự chế một mẫu.",
    "t029": "Bộ biểu mẫu lượng giá và bảng phân tích",
    "t030": "Quy trình 6 bước, session note mẫu chuẩn, khung kế hoạch tháng",
    "t031": "Ma trận chức năng giao tiếp, hồ sơ ca, phiếu hướng dẫn phụ huynh",
    "t032": "Có thoả thuận bằng văn bản về phạm vi sử dụng và thời hạn",
    "t033": "Điều kiện:",
    "t034": " Dành cho cơ sở can thiệp",
    "t035": "🏫",
    "t036": "Đào tạo nội bộ cả đội ngũ",
    "t037": "Dạy cả đội một lúc, tại chính cơ sở của bạn, để toàn trung tâm quan sát, học và thực hành cùng một cách.",
    "t038": "Thiết kế lộ trình riêng theo đội ngũ hiện có — ai cần cấp nào",
    "t039": "Dạy tại cơ sở, dùng chính trẻ của trung tâm",
    "t040": "Thường bắt đầu bằng Âm ngữ trị liệu Bậc 1–2 cho toàn đội, rồi cử một hai người đi tiếp chuyên khoa",
    "t041": "Điều kiện:",
    "t042": " Dành cho cơ sở can thiệp",
    "t043": "📋",
    "t044": "Duyệt hồ sơ ca & báo cáo định kỳ",
    "t045": "Sau khi đội đã được đào tạo, đây là lớp giữ cho chất lượng ổn định bền vững. Hồ sơ ca thật của cơ sở được giám sát và sửa theo định kỳ.",
    "t046": "Duyệt hồ sơ lượng giá và kế hoạch can thiệp của ca thật",
    "t047": "Nhận xét và điều chỉnh",
    "t048": "Báo cáo định kỳ theo tháng hoặc theo quý",
    "t049": "Dùng làm bằng chứng chất lượng khi cơ sở làm việc với phụ huynh",
    "t050": "Điều kiện:",
    "t051": " Dành cho cá nhân và cơ sở",
    "t052": "Cá nhân và cơ sở khác nhau ở đâu",
    "t053": "👤 Chuyển giao cho cá nhân",
    "t054": "Bạn là trị liệu viên đang làm nghề, muốn chắc tay trên ca của mình.",
    "t055": "Chủ yếu là ",
    "t056": "thực hành lâm sàng có giám sát",
    "t057": " — gói 4 hoặc 8 buổi",
    "t058": "Có thể thêm ",
    "t059": "duyệt hồ sơ ca",
    "t060": " nếu bạn muốn được đọc và sửa thường xuyên hơn",
    "t061": "Điều kiện: đã xong Âm ngữ trị liệu ba bậc",
    "t062": "Hỏi gói cá nhân",
    "t063": "🏢 Chuyển giao cho cơ sở can thiệp",
    "t064": "Bạn phụ trách chuyên môn một trung tâm và cần cả đội chạy cùng một chuẩn.",
    "t065": "Đào tạo in-house trọn đội ngũ tại cơ sở của bạn",
    "t066": "Quyền sử dụng giáo trình và bộ biểu mẫu trong vận hành",
    "t067": "Giám sát lâm sàng cho nhân sự chủ chốt",
    "t068": "Duyệt hồ sơ ca và báo cáo định kỳ để chất lượng không trôi",
    "t069": "Hỏi gói cơ sở",
    "t070": "Một buổi giám sát diễn ra thế nào",
    "t071": "Bạn gửi ca trước buổi",
    "t072": "Hồ sơ lượng giá, kế hoạch đang chạy, và điều bạn đang thấy bế tắc. Có clip buổi trị liệu thì càng tốt.",
    "t073": "Cùng xem lại buổi làm việc của bạn",
    "t074": "Trực tiếp tại chỗ hoặc qua clip. Không phải nghe giảng — mà là dừng lại ở từng đoạn để chỉ ra chỗ đúng, chỗ chưa, và lẽ ra nên làm gì.",
    "t075": "Sửa lại kế hoạch ngay trong buổi",
    "t076": "Ra khỏi buổi giám sát là bạn có bản kế hoạch đã chỉnh, dùng được cho buổi trị liệu kế tiếp.",
    "t077": "Ghi lại để lần sau đối chiếu",
    "t078": "Mỗi buổi có ghi chú những điểm cần theo dõi. Sau bốn hoặc tám buổi bạn nhìn lại được mình đã đổi những gì.",
    "t079": "Câu hỏi hay gặp",
    "t080": "Tôi chưa học Âm ngữ trị liệu ba bậc, đăng ký giám sát được không?",
    "t081": "Chưa được. Buổi giám sát chỉ đáng tiền khi hai bên nói cùng một ngôn ngữ chuyên môn — cùng cách lượng giá, cùng cách viết mục tiêu, cùng bộ biểu mẫu. Nếu chưa có nền đó, phần lớn buổi giám sát sẽ trôi vào việc giảng lại kiến thức cơ bản.",
    "t082": "Tôi ở tỉnh xa, chị có đến cơ sở của tôi không?",
    "t083": "Có hai cách: chị đến tận nơi, hoặc bạn quay clip buổi trị liệu gửi trước rồi cùng xem và sửa qua Zoom. Hai hình thức tính phí khác nhau — nhắn Zalo để biết chi tiết và lịch trống.",
    "t084": "Cơ sở tôi có 12 nhân sự, nên bắt đầu thế nào?",
    "t085": "Thường là đào tạo in-house Âm ngữ trị liệu Bậc 1 và Bậc 2 cho toàn đội trước, để cả trung tâm dùng chung một chuẩn quan sát và một bộ biểu mẫu. Sau đó cử một đến hai người đi tiếp chuyên khoa và nhận giám sát lâm sàng, làm người chuẩn hoá chuyên môn nội bộ.",
    "t086": "Chi phí thế nào?",
    "t087": "Bốn hạng mục tính phí riêng từng mức, tuỳ quy mô đội ngũ, số buổi giám sát và hình thức (tại chỗ hay online). Nhắn Zalo ",
    "t088": "0857389318",
    "t089": " để đặt một buổi trao đổi — buổi này không tính phí.",
    "t090": "Đặt một buổi trao đổi",
    "t091": "Kể cho chúng tôi quy mô đội của bạn và điều bạn muốn chuẩn hoá. Chúng tôi sẽ đề xuất đúng hạng mục cần — và nói rõ hạng mục nào chưa cần thiết lúc này.",
    "t092": "Nhắn Zalo 0857389318",
    "t093": "Gọi ngay"
  },
  "images": {},
  "links": {
    "link001": "https://zalo.me/0857389318",
    "link002": "#dao-tao",
    "link003": "https://zalo.me/0857389318",
    "link004": "https://zalo.me/0857389318",
    "link005": "https://zalo.me/0857389318",
    "link006": "tel:0857389318"
  },
  "alts": {},
  "placeholders": {}
};
