import { HomePageData } from "./HomePage.types";

export const homePageMockData: HomePageData = {
  "texts": {
    "t001": "Dr Owl Academy · OWLSPEAKS",
    "t002": "Thấu hiểu trẻ,",
    "t003": "đi đúng ngay từ bước đầu tiên.",
    "t004": "Khám, tư vấn và can thiệp cho trẻ có khó khăn về ",
    "t005": "ngôn ngữ, giao tiếp, phát triển",
    "t006": ". Đào tạo thực hành can thiệp và xuất bản về ",
    "t007": "ngôn ngữ — lời nói — giác quan",
    "t008": " cho trẻ Việt Nam. Mọi tài liệu ở đây đều viết bằng tiếng Việt, thích ứng cho trẻ Việt và phù hợp với văn hoá xã hội Việt Nam.",
    "t009": "Tôi là phụ huynh →",
    "t010": "Tôi là chuyên viên →",
    "t011": "Làm test nhanh cho con",
    "t012": "7",
    "t013": "đầu sách đã xuất bản",
    "t014": "3",
    "t015": "hệ đào tạo · 10 cấp",
    "t016": "600",
    "t017": "trẻ trong nghiên cứu từ vựng",
    "t018": "L2",
    "t019": "PROMPT Level 2 · người Việt đầu tiên",
    "t020": "Bộ Miệng xinh lời hay — đi kèm khoá học",
    "t021": "Bạn đang cần gì?",
    "t022": "Hãy chọn cánh cửa phù hợp với bạn",
    "t023": "Cùng nền tảng khoa học nhưng cha mẹ và người làm nghề cần hai lộ trình khác nhau.",
    "t024": "👪",
    "t025": "Tôi là phụ huynh",
    "t026": "Con chậm nói, khó tập trung, né ánh mắt, gọi không quay đầu, hay lăng xăng, phát âm ngọng, khó phát âm, kén ăn, không chơi với bạn… — bạn muốn biết con đang gặp trở ngại gì và mình làm được gì để giúp con.",
    "t027": "Đăng ký khám & lượng giá cho con",
    "t028": "Can thiệp trực tiếp tại trung tâm Ngôn ngữ trị liệu OWLSPEAKS",
    "t029": "Lớp cha mẹ 1 ngày · Khoá cầm tay chỉ việc 1–1 tám tuần",
    "t030": "Mua sách & học liệu",
    "t031": "Xem lối đi cho phụ huynh →",
    "t032": "🎓",
    "t033": "Tôi là chuyên viên",
    "t034": "Bạn đang làm nghề hoặc mới vào nghề, muốn có một hệ thống chuẩn để tự tin và thành công trên nhiều trẻ.",
    "t035": "Ba hệ đào tạo: Âm ngữ trị liệu · Chơi lớn · Miệng xinh lời hay",
    "t036": "Trọn một hệ → Trị liệu viên Tài năng",
    "t037": "Thực hành lâm sàng có giám sát",
    "t038": "Chuyển giao cho cá nhân và cơ sở",
    "t039": "Xem chương trình đào tạo →",
    "t040": "Bản đồ",
    "t041": "Tháp đào tạo Dr Owl Academy",
    "t042": "Đọc từ dưới lên: một thân, hai cành, một đỉnh — và một nhánh riêng cho cha mẹ. Bấm vào từng bậc để xem nội dung.",
    "t043": "Nhánh Cha mẹ — đi riêng",
    "t044": "Lớp cha mẹ 1 ngày",
    "t045": "Học trực tiếp · không cần nền tảng",
    "t046": "999.999đ",
    "t047": "Dạy con 24/7",
    "t048": "Coaching 1–1 online · 8 tuần",
    "t049": "1 buổi Zoom + 1 clip mỗi tuần",
    "t050": "Cha mẹ muốn đi sâu hơn thì bước sang nhánh làm nghề, vào thẳng ",
    "t051": "Âm ngữ trị liệu Bậc 1",
    "t052": ".",
    "t053": "Đỉnh · Bậc 5",
    "t054": "Can thiệp đa trường phái",
    "t055": "Tích hợp các công cụ và phương pháp trên cùng một đứa trẻ",
    "t056": "Hành vi ngôn ngữ",
    "t057": "Suy đoán tâm trí",
    "t058": "Can thiệp sớm + PROMPT",
    "t059": "Tích hợp giác quan – vận động",
    "t060": "Vào đỉnh cần: ",
    "t061": "xong ÂNTL ba bậc",
    "t062": " và trọn ",
    "t063": "ít nhất một chuyên khoa",
    "t064": "Cành 1 · Bậc 4",
    "t065": "CHƠI LỚN",
    "t066": "Chuyên khoa phát triển & vui chơi",
    "t067": "C1 Chơi lớn",
    "t068": "C2 Nói chơi",
    "t069": "C3 Chơi cùng giác quan",
    "t070": "Cành 2 · Bậc 4",
    "t071": "MIỆNG XINH LỜI HAY",
    "t072": "Chuyên khoa âm lời nói",
    "t073": "C1 Cấu âm",
    "t074": "C2 Âm vị",
    "t075": "C3 Bàn tay kì diệu",
    "t076": "C4 Trẻ nói khó và đồng mắc",
    "t077": "Hai cành học song song được · ",
    "t078": "MXLH Cấp 4 bắt buộc phải có ÂNTL Bậc 1 và Bậc 2",
    "t079": "Thân cây · Bậc 3",
    "t080": "ÂNTL Bậc 3 — Chuyên sâu",
    "t081": "AAC chuyên sâu · may đo chương trình trị liệu âm ngữ phức hợp · triển khai hoạt động dạy · lượng giá động",
    "t082": "Thân cây · Bậc 2",
    "t083": "ÂNTL Bậc 2 — Trị liệu giao tiếp",
    "t084": "Công thức thiết kế mục tiêu · tháp dạy học 4Th · quy trình can thiệp khép kín · kịch bản trị liệu",
    "t085": "Nền · Bậc 1 — ai làm nghề cũng phải qua",
    "t086": "ÂNTL Bậc 1 — May đo & Lượng giá",
    "t087": "Bảng kiểm lâm sàng giao tiếp chức năng · mốc phát triển · dấu hiệu cảnh báo · phân tích case thực tế · viết mục tiêu chuẩn y khoa · không yêu cầu nền tảng",
    "t088": "Danh hiệu đạt được",
    "t089": "Mỗi bậc, mỗi cấp",
    "t090": "Chứng nhận hoàn thành",
    "t091": "Trọn hệ Âm ngữ trị liệu",
    "t092": "Trị liệu viên Tài năng — hệ Âm ngữ trị liệu",
    "t093": "Trọn hệ Chơi lớn",
    "t094": "Trị liệu viên Tài năng — hệ Trị liệu ứng dụng Chơi",
    "t095": "Trọn hệ Miệng xinh lời hay",
    "t096": "Trị liệu viên Tài năng — hệ Kích tạo âm chuẩn y khoa",
    "t097": "Đỉnh tháp",
    "t098": "⭐ Trị liệu viên Tinh hoa",
    "t099": "Chuyển giao & giám sát",
    "t100": "Thực hành lâm sàng có giám sát · quyền dùng giáo trình & biểu mẫu · đào tạo in-house · duyệt hồ sơ ca. Bốn hạng mục tính phí riêng.",
    "t101": "Xem chi tiết",
    "t102": "Một buổi trị liệu tại OWLSPEAKS",
    "t103": "Ba việc OWLSPEAKS làm",
    "t104": "Từ buổi khám đầu tiên, tới lớp cho cha mẹ, tới đào tạo và chuyển giao cho người làm nghề — cùng một hệ thống, cùng một bộ công cụ.",
    "t105": "🩺 Khám & can thiệp",
    "t106": "Lượng giá toàn diện ngôn ngữ — lời nói — giác quan — vui chơi bằng những công cụ chuẩn hoá, khoa học, cho ra kết quả bằng số liệu cụ thể và may đo kế hoạch can thiệp cá nhân khớp với riêng từng bé.",
    "t107": "Đăng ký khám",
    "t108": "👪 Lớp cho cha mẹ",
    "t109": "Lớp một ngày để hiểu con và có thể áp dụng ngay tối nay — hoặc Khoá huấn luyện cầm tay chỉ việc 1–1 online tám tuần, trên chính con bạn và bạn.",
    "t110": "Xem lớp cha mẹ",
    "t111": "🎓 Đào tạo & chuyển giao",
    "t112": "Ba hệ, mười cấp, đích đến mỗi cấp là một nhóm kĩ năng năng lực lâm sàng thành thục. Kèm thực hành lâm sàng có giám sát và chuyển giao cho trung tâm.",
    "t113": "Xem chương trình",
    "t114": "Người đứng sau hệ thống",
    "t115": "TS.BS. Nguyễn Hoàng Oanh",
    "t116": "Tác giả bộ giáo trình ",
    "t117": "Miệng xinh lời hay",
    "t118": " — Cấu âm (2023), Can thiệp âm vị (2025), Bản đồ giải phẫu phát âm (2026) — và bảy đầu sách về ngôn ngữ, chơi, giác quan cho trẻ Việt Nam.",
    "t119": "Trị liệu viên ngôn ngữ người Việt ",
    "t120": "đầu tiên hoàn thành PROMPT Level 2",
    "t121": "Huấn luyện viên",
    "t122": " của ",
    "t123": "Hanen Canada",
    "t124": " (từ 2015) và ",
    "t125": "The Project ImPACT",
    "t126": " Hoa Kỳ (từ 2021)",
    "t127": "Luận án tiến sĩ về ",
    "t128": "Trị liệu phát âm cho trẻ khe hở môi vòm",
    "t129": " — Đại học Y Hà Nội, 2021",
    "t130": "Đã được đào tạo nhiều chương trình can thiệp có bằng chứng khoa học: ",
    "t131": "PECS",
    "t132": ", ",
    "t133": "Nuffield",
    "t134": ", ",
    "t135": "Myofunctional therapy",
    "t136": "…",
    "t137": "Đồng chủ nhiệm nghiên cứu ",
    "t138": "100 từ đầu tiên",
    "t139": " trên 600 trẻ em Việt Nam ba miền",
    "t140": "Tôi chưa biết bắt đầu từ đâu?",
    "t141": "Nhắn cho chúng tôi về con bạn hoặc về trẻ mà bạn đang vướng mắc. Chúng tôi sẽ chỉ đúng cửa cần vào — cần hẹn lịch khám, tham gia khoá học, hay chỉ một cuốn sách là đủ.",
    "t142": "Nhắn Zalo 0866620583",
    "t143": "Gọi ngay"
  },
  "images": {
    "img001": "/images/bo-sach-va-cong-cu-dr-owl-academy-8a477b90.jpg",
    "img002": "/images/ts-bs-nguyen-hoang-oanh-lam-viec-voi-tre-tai-owl-5cff1076.jpg",
    "img003": "/images/ts-bs-nguyen-hoang-oanh-bb8a8095.jpg"
  },
  "links": {
    "link001": "#phu-huynh",
    "link002": "#dao-tao",
    "link003": "#test-nhanh",
    "link004": "#phu-huynh",
    "link005": "#dao-tao",
    "link006": "#lop-cha-me/p1",
    "link007": "#lop-cha-me/p2",
    "link008": "#dao-tao/dinh",
    "link009": "#dao-tao/choi",
    "link010": "#dao-tao/mxlh",
    "link011": "#dao-tao/ancs-3",
    "link012": "#dao-tao/ancs-2",
    "link013": "#dao-tao/ancs-1",
    "link014": "#chuyen-giao",
    "link015": "#phu-huynh/kham",
    "link016": "#lop-cha-me",
    "link017": "#dao-tao",
    "link018": "https://zalo.me/0866620583",
    "link019": "tel:0866620583"
  },
  "alts": {
    "alt001": "Bộ sách và công cụ Dr Owl Academy",
    "alt002": "TS.BS. Nguyễn Hoàng Oanh làm việc với trẻ tại OWLSPEAKS",
    "alt003": "TS.BS. Nguyễn Hoàng Oanh"
  },
  "placeholders": {}
};
