import { ContactPageData } from "./ContactPage.types";

export const contactPageMockData: ContactPageData = {
  "texts": {
    "t001": "Liên hệ",
    "t002": "Nói chuyện với chúng tôi",
    "t003": "Bạn không cần biết mình cần gì trước khi nhắn. Kể tình huống của bạn — chúng tôi sẽ chỉ đúng cửa.",
    "t004": "💬",
    "t005": "Zalo",
    "t006": "Cách nhanh nhất. Nhắn giờ hành chính, thường trả lời trong ngày.",
    "t007": "Mở Zalo 0866620583",
    "t008": "📞",
    "t009": "Hotline",
    "t010": "Gọi khi cần trao đổi gấp hoặc muốn đặt lịch khám ngay.",
    "t011": "0866620583",
    "t012": "📅",
    "t013": "Nhóm Zalo lịch khai giảng",
    "t014": "Nơi cập nhật lịch các học phần sớm nhất, không bỏ lỡ đợt đăng ký.",
    "t015": "Tham gia nhóm",
    "t016": "Nhắn gì cho nhanh được tư vấn",
    "t017": "Nếu bạn là phụ huynh",
    "t018": "Con mấy tuổi, mấy tháng",
    "t019": "Điều bạn lo nhất — nói một câu thôi cũng được",
    "t020": "Con đã đi khám ở đâu chưa, kết quả thế nào",
    "t021": "Bạn ở tỉnh/thành nào (để biết học trực tiếp hay online)",
    "t022": "Nhắn ngay",
    "t023": "Nếu bạn là chuyên viên / trung tâm",
    "t024": "Bạn đang làm ở vị trí nào, bao lâu rồi",
    "t025": "Ca bạn đang vướng — hoặc kỹ năng bạn thấy mình thiếu",
    "t026": "Đội của bạn bao nhiêu người (nếu hỏi gói chuyển giao)",
    "t027": "Bạn muốn học online, trực tiếp, hay in-house tại trung tâm",
    "t028": "Nhắn ngay",
    "t029": "📍",
    "t030": "Địa chỉ",
    "t031": "378 Minh Khai, Hà Nội",
    "t032": "✉",
    "t033": "Email",
    "t034": "amngutrilieutreem@gmail.com",
    "t035": "🕐",
    "t036": "Giờ làm việc",
    "t037": "8–17h, thứ 2 – thứ 6",
    "t038": "(theo lịch hẹn)"
  },
  "images": {},
  "links": {
    "link001": "https://zalo.me/0866620583",
    "link002": "tel:0866620583",
    "link003": "https://tinyurl.com/thamgiaDrOwlAcademy",
    "link004": "https://zalo.me/0866620583",
    "link005": "https://zalo.me/0866620583"
  },
  "alts": {},
  "placeholders": {}
};
